# theme.toml template for Airspace Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for documentation

name = "Airspace Hugo"
license = "Themefisher Free Template License"
licenselink = "https://github.com/karju-dev/airspace-hugo/blob/master/LICENSE.md"
description = "Hugo porting for Themefisher's Airspace theme"
homepage = "https://github.com/karju-dev/airspace-hugo"
tags = ["Themefisher", "bootstrap", "company"]
features = ["responsive", "portfolio"]
min_version = 0.19

[author]
  name = "Giacomo Mariani"
  homepage = ""

# If porting an existing theme
[original]
  name = "airspace"
  homepage = "https://themefisher.com/products/airspace-free-bootstrap-website-template/"
  repo = "https://github.com/themefisher/airspace-free-html5-agency-template"
